apiVersion: v2
name: rustrial-aws-eks-iam-auth-controller
description: Kubernetes operator which consolidates custom resources into `aws-auth` ConfigMap.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 0.0.0

annotations:
  artifacthub.io/crds: |
    - kind: IAMIdentityMapping
      version: v1alpha1
      name: iamidentitymapping
      displayName: AWS IAM identity mapping
      description: Mapping AWS IAM User or Role ARN to Kubernetes username and groups.
  artifacthub.io/crdsExamples: |
    - apiVersion: iamauthenticator.k8s.aws/v1alpha1
      kind: IAMIdentityMapping
      metadata:
      name: kubernetes-admin-user
      spec:
        arn: arn:aws:iam::XXXXXXXXXXXX:user/KubernetesAdmin
        username: kubernetes-admin
        groups:
        - system:masters
  artifacthub.io/license: Unlicense OR MIT OR Apache-2.0
